- name: Deploy Dockge (docker-compose stacks management)
  hosts: apps_vm
  roles:
    - homelab-app
  vars:
    homelab_app_name: dockge
    homelab_app_apps_domain: "{{ homeserver_domain }}"
    homelab_app_internal_port: 5001
    homelab_app_volume_names:
      - data
    # homelab_app_backups:
    #   - volume: repo
    #     cron: "35 6 * * *"
