---
homeserver_domain: staging.home
dns_ip: 10.142.1.2
gateway_ip: "{{ ansible_host }}"
legacy_server_ip: 10.142.1.200
mainhost_ip: 10.142.10.10

homelab_app_backups_rclone_remote: r2:/homelab-backups-staging
# Legacy settings
remote_backups_enabled: true
remote_backups_path: homelab-backups-staging
