---
- name: General settings on a linux server
  ansible.builtin.import_playbook: "./linux_server.yaml"
- name: Setup apps host
  ansible.builtin.import_playbook: "./setup_apps_host.yaml"
- name: "Setup the backup summaries"
  ansible.builtin.import_playbook: "./backup-summaries.yaml"

- name: Setup traefik
  ansible.builtin.import_playbook: "./traefik.yml"

- name: Home Assistant
  ansible.builtin.import_playbook: "./apps/home-assistant/main.yaml"
- name: Zigbee2MQTT
  ansible.builtin.import_playbook: "./apps/z2m/main.yaml"

- name: Paperless
  ansible.builtin.import_playbook: "./apps/paperless/main.yaml"
- name: Wiki
  ansible.builtin.import_playbook: "./apps/wiki/main.yaml"
- name: Tasks.md
  ansible.builtin.import_playbook: "./apps/tasks-md/main.yaml"

- name: Uptime-Kuma
  ansible.builtin.import_playbook: "./apps/uptime-kuma/main.yaml"
- name: Dockge
  ansible.builtin.import_playbook: "./apps/dockge/main.yaml"


- name: servarr
  ansible.builtin.import_playbook: "./servarr.yaml"
- name: Jellyfin
  ansible.builtin.import_playbook: "./apps/jellyfin/main.yaml"
- name: Navidrome
  ansible.builtin.import_playbook: "./apps/navidrome/main.yaml"
- name: Feishin
  ansible.builtin.import_playbook: "./apps/feishin/main.yaml"
- name: MusicBrainz Picard
  ansible.builtin.import_playbook: "./apps/picard/main.yaml"
- name: slskd
  ansible.builtin.import_playbook: "./apps/slskd/main.yaml"
- name: slsk-batchdl
  ansible.builtin.import_playbook: "./slsk_batchdl.yaml"

- name: Homepage
  ansible.builtin.import_playbook: "./apps/homepage/main.yaml"
