---
- name: Install radarr
  ansible.builtin.import_playbook: "./apps/radarr/main.yaml"
- name: Install sonarr
  ansible.builtin.import_playbook: "./apps/sonarr/main.yaml"
- name: Install bazarr
  ansible.builtin.import_playbook: "./apps/bazarr/main.yaml"
- name: Install lidarr
  ansible.builtin.import_playbook: "./apps/lidarr/main.yaml"
- name: Install prowlarr
  ansible.builtin.import_playbook: "./apps/prowlarr/main.yaml"
- name: Install qbittorrent
  ansible.builtin.import_playbook: "./apps/qbittorrent/main.yaml"
