---
ansible_host: 10.142.10.10
ansible_user: admin
apps_root: "/srv/apps"
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
gpu_passthrough_enabled: false
