- name: "Deploy Alloy"
  hosts: monitoring
  roles:
    - homelab-app
  vars:
    homelab_app_name: alloy
    homelab_app_cpus: 1.0
    homelab_app_apps_domain: "{{ homeserver_domain }}"
    homelab_app_internal_port: 12345
    homelab_app_volume_names:
      - data
    homelab_app_backups:
      - volume: data
        cron: "0 2 * * *"  # Daily backup at 2 AM
  pre_tasks:
    - name: Monitoring setup
      ansible.builtin.import_tasks: "{{ playbooks_root }}/tasks/monitoring-setup.yaml"
    - name: Ensure Alloy config directory exists
      file:
        path: "{{ homelab_app_target_root_dir }}/config"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ default_admin_group }}"
        mode: "{{ default_admin_dir_mode }}"
    - name: Render Alloy configuration template
      template:
        src: "./config/alloy-config.alloy.j2"
        dest: "{{ homelab_app_target_root_dir }}/config/alloy-config.alloy"
        group: "{{ default_admin_group }}"
        mode: "{{ default_admin_file_mode }}"
